### PR TITLE
Rework Clients, Tools, and Data Prepper section

### PR DESCRIPTION
**Pull request by Naarcha-AWS**
Signed-off-by: Naarcha-AWS <naarcha@amazon.com>

Closes part of #1036 

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kolchfa-aws — APPROVED** [review]
LGTM

**Comment by hdhalter** [comment]
@kolchfa-aws - Did you want to change the order of the list of clients? Python, .NET, Ruby, etc.? Or should we alphabetize them?

**Comment by kolchfa-aws** [comment]
We would like to revisit this order and just list languages. I will reorganize these pages after the 2.4 release.

**Comment by hdhalter** [comment]
OK, then we just need to move Grafana to Tools. Thanks!

**Review by hdhalter — APPROVED** [review]

**Pull request merged**
