### PR TITLE
Update the example of the multiple terms aggregation by muliple orders.

### LINKED ISSUE #7037: [DOC] Update the document for multiple terms aggregation
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

The current document about the multiple terms aggregation is not accurate. In the document(https://opensearch.org/docs/latest/aggregations/bucket/multi-terms/), it gives an example. And it implies that multiple terms aggregation only accepts one order. But in fact, it accepts multiple orders like the following:
```
GET sample-index100/_search
{
  "size": 0, 
  "aggs": {
    "hot": {
      "multi_terms": {
        "terms": [{
          "field": "region" 
        },{
          "field": "host" 
        }],
        "order":[ {"max-cpu": "desc"},  {"max-memory": "desc"}] <=== multiple orders
      },
      "aggs": {
        "max-cpu": { "max": { "field": "cpu" } },
        "max-memory":  { "max": { "field": "memory" } }
      }      
    }
  }
}
```
Please help to update the document, and I think this is an important and valuable feature for the multiple terms aggregation.

### PR DESCRIPTION
**Pull request by Zhikai-VM**
### Description
Update the example of the multiple terms aggregation.

### Issues Resolved
Closes #7037

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ankyhe** [comment]
I suggest we don't remove the original example, but add a new one.  Because if it needs only 1 order, it could use original one.  If we change document like this way, it could confuse the old order style is not supported.  But it is not true, it can support both one order with `{...}` or multiple order with `[...]`.

**Comment by Zhikai-VM** [comment]
> I suggest we don't remove the original example, but add a new one. Because if it needs only 1 order, it could use original one. If we change document like this way, it could confuse the old order style is not supported. But it is not true, it can support both one order with `{...}` or multiple order with `[...]`.

I got your point, but the current document is not correct. I am trying to fix it to make it accurate.

**Comment by hdhalter** [comment]
@bowenlan-amzn - What are your thoughts on this?

**Comment by Zhikai-VM** [comment]
> #7037

Please refer to the update in PR: https://github.com/opensearch-project/OpenSearch/pull/13400

**Comment by Zhikai-VM** [comment]
> @bowenlan-amzn - What are your thoughts on this?

Please refer to the update in PR: https://github.com/opensearch-project/OpenSearch/pull/13400

**Comment by hdhalter** [comment]
Hi @dblock - Can you please comment with your thoughts? Thanks.

**Comment by dblock** [comment]
The current example is incorrect, if I understand correctly it has to be an array of orders, even with 1 order. There's no point in having an array of 1 and then another example with an array of 2, is there?

**Comment by Zhikai-VM** [comment]
> The current example is incorrect, if I understand correctly it has to be an array of orders, even with 1 order. There's no point in having an array of 1 and then another example with an array of 2, is there?

As far as I know, there is no example of array in the offical doc.

**Comment by ankyhe** [comment]
> The current example is incorrect, if I understand correctly it has to be an array of orders, even with 1 order. There's no point in having an array of 1 and then another example with an array of 2, is there?

@dblock As current official document, the multi-term example is as below:
```
GET sample-index100/_search
{
  "size": 0, 
  "aggs": {
    "hot": {
      "multi_terms": {
        "terms": [{
          "field": "region" 
        },{
          "field": "host" 
        }],
        "order": {"max-cpu": "desc"}
      },
      "aggs": {
        "max-cpu": { "max": { "field": "cpu" } }
      }      
    }
  }
}
```
@Zhikai-VM wants to revise it as:
```
GET sample-index100/_search
{
  "size": 0, 
  "aggs": {
    "hot": {
      "multi_terms": {
        "terms": [{
          "field": "region" 
        },{
          "field": "host" 
        }],
        "order": [ {"max-cpu": "desc"}, {"max-mem": "asc"}]
      },
      "aggs": {
        "max-cpu": { "max": { "field": "cpu" } },
        "max-mem": { "min": { "field": "mem"}}
      }      
    }
  }
}
```
to keep the official document accordance with this PR: https://github.com/opensearch-project/OpenSearch/pull/13400

**Comment by Zhikai-VM** [comment]
Hi @dblock , what do you think about this? I prefer to use an array for the 'order' field. We can pass one order or multiple orders in this field.

**Comment by dblock** [comment]
This looks good to me, can we merge @hdhalter ?

**Review by Naarcha-AWS — APPROVED** [review]

**Comment by Zhikai-VM** [comment]
Thanks @dblock @bowenlan-amzn!

**Pull request merged**
