### PR TITLE
Add include_named_queries_score to docs

### LINKED ISSUE #6278: [DOC] add include_named_queries_score for returning scores for named queries
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
https://github.com/opensearch-project/OpenSearch/pull/11626
Pushing a change here that allows clients to get the matched queries with its respective scores when the `include_named_queries_score` flag is passed
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

### PR DESCRIPTION
**Pull request by kolchfa-aws**
Closes #6278

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by natebower — APPROVED** [review]
@kolchfa-aws Just a global comment on the table re: whether the parameter names and "true" and "false" should be in code font. Otherwise, LGTM.

**Comment by kolchfa-aws** [comment]
@Dharin-shah Is this applicable to 2.12?

**Comment by Dharin-shah** [comment]
> @Dharin-shah Is this applicable to 2.12?

no, 3.0.0 and beyond. Also should we wait for the main feature PR to be merged before merging this? i need to make some changes based on some review comments

**Comment by kolchfa-aws** [comment]
@Dharin-shah Yes, we will wait until the code is merged to merge this PR. Thanks!

**Comment by Dharin-shah** [comment]
We can merge this as well now :)

**Pull request merged**
