### PR TITLE
Adding OS matrix changelog and remove CentOS7 as it is approaching EOL

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
Adding OS matrix changelog and remove CentOS7 as it is approaching EOL

### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-build/issues/4379
https://github.com/opensearch-project/opensearch-build/issues/4681

### Version
~~2.15.0+~~
2.16.0

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Naarcha-AWS** [comment]
@peterzhuamazon: Would this be better as a separate file?

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon: Would this be better as a separate file?

Yes it would be better if the compatibility section is standalone.
Would you be able to help on this, Nate ?
I am not very familiar with the docs repo structure 😄 

Thanks.a

**Comment by peterzhuamazon** [comment]
We are moving this change to 2.16.0 due to issues here:
* https://github.com/opensearch-project/opensearch-build/issues/4379#issuecomment-2161600573

**Comment by hdhalter** [comment]
@peterzhuamazon - Is this change still coming in 2.16?

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon - Is this change still coming in 2.16?

Yes @hdhalter , we are ready to get it merged for 2.16.0.

Thanks.

**Comment by hdhalter** [comment]
Hi @Naarcha-AWS , can you please update for 2.16 as per https://github.com/opensearch-project/documentation-website/pull/7287#issuecomment-2163286681. Thanks!

**Comment by Naarcha-AWS** [comment]
@hdhalter and @peterzhuamazon: This on my radar. I'll go ahead and update the PR to add the new file.

**Comment by Naarcha-AWS** [comment]
@peterzhuamazon: Closing this in favor of #7821. Could you take a look at that PR and make sure the new page captures all the information it should?

**Pull request closed without merging**
