### PR TITLE
Update docs for remote store backpressure stats

### PR DESCRIPTION
**Pull request by BhumikaSaini-Amazon**
### Description
Update docs for changes from https://github.com/opensearch-project/OpenSearch/pull/10524

### Issues Resolved
Related to:
* https://github.com/opensearch-project/OpenSearch/issues/10501
* https://github.com/opensearch-project/OpenSearch/issues/10365

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by hdhalter** [comment]
@BhumikaSaini-Amazon - Which release is this targeting?

**Comment by BhumikaSaini-Amazon** [comment]
@hdhalter this would be for 2.12

**Review by Naarcha-AWS — APPROVED** [review]

**Comment by BhumikaSaini-Amazon** [comment]
@Naarcha-AWS, thanks for helping with the review! The required PRs for the respective code changes are merged. We can go ahead with merging this PR for 2.12 release. 

Thanks!

**Comment by hdhalter** [comment]
Fixes https://github.com/opensearch-project/documentation-website/issues/5400

**Pull request merged**
