### PR TITLE
updating JWT authentication section

### PR DESCRIPTION
**Pull request by dvas0004**
### Description
1. `enabled: true` is just plain wrong and will fail. corrected the sample config
2. Adding troubleshooting tips that I came across

side note... configuration documentation should really contain references to the currently "hidden" parameters of 

```yml
opensearch_security.auth.type: "jwt"
opensearch_security.jwt.url_param: your_param_name_here
```

only reason I came across this is looking at the source code...

### Issues Resolved
Helps resolve user complain on the wrong config mentioned in https://github.com/opensearch-project/security-dashboards-plugin/issues/872

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Naarcha-AWS** [comment]
@dvas0004: Looks good. Your commit requires the DCO sign-off to pass the PR check.
See [fix DCO](https://github.com/src-d/guide/blob/9171d013c648236c39faabcad8598be3c0cf8f56/developer-community/fix-DCO.md#how-to-add-sign-offs-retroactively) for details.

**Comment by Naarcha-AWS** [comment]
@cwillum: Want to review this one?

**Review by cwillum — APPROVED** [review]
LGTM.

**Comment by dvas0004** [comment]
DCO sign-off added

**Comment by hdhalter** [comment]
@Naarcha-AWS - can we merge this?

**Comment by Naarcha-AWS** [comment]
@dvas0004: I added some copy edits to this PR. These edits can be found on PR #1279

**Pull request closed without merging**
