### PR TITLE
Navigational improvement

### PR DESCRIPTION
**Pull request by aetter**
### Description
Bundles related items together and (I believe?) makes things more organized and easier to scan. For reviewers, pull the branch, build it locally, get a feel for it, let me know what you think.

### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Screen Shot 2021-06-09 at 7 20 15 PM

### CODE REVIEW

**Comment by liz-snyder-aws** [comment]
Pushed a few minor capitalization fixes. 

Few minor things: 
- Should cat and task APIs go within the API reference?
- Is the About Index Management topic really necessary? Only contains one sentence. 

Otherwise looks great to me.

**Review by elfisher — CHANGES_REQUESTED** [review]
This looks good to me. Only change I'd request is that we name Clients -> Clients and Tools

**Comment by keithhc2** [comment]
Looks good after the recent commits

**Comment by ashwinkumar12345** [comment]
Looks good to me.

**Review by ashwinkumar12345 — COMMENTED** [review]
Looks good.

**Pull request merged**
