### PR TITLE
Fix debian installatation instructions in 1.3

### PR DESCRIPTION
**Pull request by hdhalter**
### Description
Creates a variable for the version number so the version is correct in the APT repository section.

### Issues Resolved
Fixes https://github.com/opensearch-project/documentation-website/issues/4833

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kolchfa-aws** [comment]
@peterzhuamazon Could you review this PR to ensure we're specifying the version correctly?

**Comment by hdhalter** [comment]
@peterzhuamazon - Note that this PR is for 1.3 only. Should we also update 2.9 - 2.5? See https://opensearch.org/docs/2.9/install-and-configure/install-opensearch/debian/#install-opensearch-from-an-apt-repository. Thanks.

**Review by peterzhuamazon — CHANGES_REQUESTED** [review]
On both apt or yum installation, 1.x/2.x keyword must stay unchanged, as both repos will contain all the versions from its corresponding major version.

It is hardcoded in S3 bucket on the folder name as 1.x/2.x, and changing this will fail the installation.

Thanks.

**Comment by hdhalter** [comment]
@peterzhuamazon - updated to 1.x - please review. Thanks!

**Pull request merged**
