### PR TITLE
[WIP] Update compatibility chart for OS support related changes

### PR DESCRIPTION
**Pull request by peterzhuamazon**
### Description
[NodeJS18 Upgrade] Update compatibility chart for NodeJS18 related changes

### Issues Resolved
https://github.com/opensearch-project/opensearch-build/issues/1563
https://github.com/opensearch-project/opensearch-build/issues/3743
https://github.com/opensearch-project/documentation-website/issues/4303

### Checklist
- [ ] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
We can hold this until the release of 2.10.0 @hdhalter .

Thanks.

**Review by hdhalter — APPROVED** [review]

**Comment by bbarani** [comment]
This is not targeted for 2.10.0 release.

**Review by bbarani — CHANGES_REQUESTED** [review]
We will still support all the OS on the current list for 2.10.0 version but we need to add the deprecation notice for future version based on CentOS7 EOL date.

**Comment by Naarcha-AWS** [comment]
@peterzhuamazon: Do we still need update this compatibility chart?

**Comment by Naarcha-AWS** [comment]
@peterzhuamazon: Going to close this for now. Feel free to reopen it if we should merge this one.

**Comment by bbarani** [comment]
@Naarcha-AWS A compatibility matrix for OpenSearch version would be needed when CentOS reaches EOL on June 30, 2024. We should plan the release and

**Comment by Naarcha-AWS** [comment]
@bbarani: Should we just add a simple warning about the sun-setting of CentOS to the compatibility matrix page? Would that work until we can address the compatibility matrix?

**Comment by bbarani** [comment]
> @bbarani: Should we just add a simple warning about the sun-setting of CentOS to the compatibility matrix page? Would that work until we can address the compatibility matrix?

This might have wider impact for native plugins like K-NN. @peterzhuamazon Can you please list the impacts of sunsetting support for CentOS version? CC: @vamshin @navneet1v

**Comment by navneet1v** [comment]
@peterzhuamazon , @bbarani with this PR, AL2 support will be removed. This can lead to big customer impact.

**Comment by peterzhuamazon** [comment]
Close this PR.
The CentOS7 deprecation notice is here:
https://github.com/opensearch-project/opensearch-build/blob/2.12.0/release-notes/opensearch-release-notes-2.12.0.md#deprecation-notice

**Pull request closed without merging**
