### PR TITLE
fix: mget http method typo

### PR DESCRIPTION
**Pull request by BagchiMB**
### Description
Was working with mget, from the docs made a GET request, but it was resolved with an error saying the response body can't be sent with GET requests, changed it to a POST request it started working, this is a quick PR which might help someone with some hassle.

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kolchfa-aws** [comment]
HI @BagchiMB! I just tried both GET and POST and they worked:

```
GET /_mget
{
  "docs": [
    {
      "_index": "shakespeare",
      "_id": "1"
    },
    {
      "_index": "shakespeare",
      "_id": "2"
    }
  ]
}
```

```
POST /_mget
{
  "docs": [
    {
      "_index": "shakespeare",
      "_id": "1"
    },
    {
      "_index": "shakespeare",
      "_id": "2"
    }
  ]
}
```
Would you share the exact setup and request that you used? We can add the POST to HTTP methods for sure.

**Comment by kolchfa-aws** [comment]
Yes, I think that seems to be a client problem. Given this, if you'd like to close this PR, I can add the POST method and remove the extra line in another PR.

**Comment by BagchiMB** [comment]
That seems cool to me, I am trying to start my open-source journey right now, and I would like to merge this PR, by making necessary changes, but if you think that would be a greater hassle, and you can do this in a better fashion in a separate PR, I totally understand. 

I couldn't understand what were you saying with the extra line, a little bit light on that would be pretty generous of you.

**Comment by kolchfa-aws** [comment]
@BagchiMB Sure, we'd love your help! Here's what you can do in this PR:
1. Add POST to Path and HTTP methods so they are
```
GET _mget
GET <index>/_mget
POST _mget
POST <index>/_mget
``
2. Remove an extra new line between the GET and the request body in the second example. Having that extra space between the header and the body will prevent the curl from working. So the example should be

```
Example of specifying index in URL

GET sample-index1/_mget
{
  "docs": [
    {
      "_id": "1",
      "_source": false
    },
    {
      "_id": "2",
      "_source": [ "Director", "Title" ]
    }
  ]
}
```
Thanks!

**Comment by BagchiMB** [comment]
Thanks for letting me work on this.

I made the changes, I was also thinking of making one of the methods in the example POST, just for variety and better understanding.

**Comment by kolchfa-aws** [comment]
Thanks so much, @BagchiMB! We normally list the GET method in examples and we list both in Path and HTTP methods. That said, we have an [API template](https://github.com/opensearch-project/documentation-website/blob/bbd95662c1f1a49ad7eb69519181df347fcb8c9a/templates/API_TEMPLATE.md) that this file (like many other files in the API section :) does not conform to. If you'd like to reorder the sections to follow the template, that would be another great improvement for consistency. If not, this PR is ready to merge.

**Comment by BagchiMB** [comment]
Hi, @kolchfa-aws I made the necessary changes to the ordering, you can check it out once

**Review by kolchfa-aws — APPROVED** [review]

**Pull request merged**
