### PR TITLE
[DOC] Move VisBuilder page to subpage under Visualize

### PR DESCRIPTION
**Pull request by vagimeli**
Signed-off-by: vagimeli <vagimeli@amazon.com>

### Description
Move page to subpage under Visualize; this is a task related to the doc site restructuring initiative

### Issues Resolved
##2208

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by vagimeli** [comment]
@Naarcha-AWS I changed the navigation text to move this page to a subpage under the new Visualize main page. See issue #1402 for reference.

**Comment by vagimeli** [comment]
@Naarcha-AWS Can we move this page? We've merged #1402

**Comment by vagimeli** [comment]
@Naarcha-AWS Will you confirm the front matter structure is correct? I'm moving this page as part of the TOC restructure. Thanks!

**Comment by Naarcha-AWS** [comment]
Closing since this is now moved under visualize.

**Pull request closed without merging**
