### PR TITLE
include performance tuning documentation for opensearch indexing scenarios

### LINKED ISSUE #4602: [DOC] Add indexing performance tuning doc.
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Add documentation with performance tuning recommendations for indexing workloads based on opensearch benchmark experiments. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

### PR DESCRIPTION
**Pull request by akashsha1**
### Description
This document describes the configurations that were used to tune indexing workload to optimize performance by 60%. They are best as recommendations in documentation so a customer can choose to apply them.

### Issues Resolved
Closes #4602

### Checklist
- [X] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kolchfa-aws** [comment]
@akashsha1 Thanks! The text looks good but it looks like when resolving DCO, you accidentally signed other people's commits and now they are listed in this PR. Could you do an interactive rebase and remove your signature from other commits while leaving it for your commits? Once the correct commits are signed off, I can merge the PR.

**Comment by kolchfa-aws** [comment]
Or, if you prefer, you can just close this PR, create a new branch, and copy the file there and raise another PR. It might be easier.

**Comment by akashsha1** [comment]
> Or, if you prefer, you can just close this PR, create a new branch, and copy the file there and raise another PR. It might be easier.

I like this approach. Simple and clean :) thanks. Here is the PR: https://github.com/opensearch-project/documentation-website/pull/4714

**Comment by kolchfa-aws** [comment]
Closing this PR in favor of #4714

**Pull request closed without merging**
