### PR TITLE
Add documentation for new recovery setting

### PR DESCRIPTION
**Pull request by andrross**
Related to https://github.com/opensearch-project/OpenSearch/pull/10349

This is a newly introduced setting in 2.11

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kotwanikunal — APPROVED** [review]

**Comment by hdhalter** [comment]
Hi @andrross - Is this ready for a doc review?

**Comment by andrross** [comment]
> Hi @andrross - Is this ready for a doc review?

Yes, it's ready!

**Review by kolchfa-aws — APPROVED** [review]
LGTM. Thanks, @andrross!

**Review by natebower — APPROVED** [review]
LGTM

**Pull request merged**
