### PR TITLE
Document Intervals Query

### LINKED ISSUE #415: [FEATURE] Document Intervals Query
Add documentation for the full-text intervals query.

### PR DESCRIPTION
**Pull request by mattweber**
### Description
Add intervals query documentation to full text query dsl section.  Cover all original functionality as well as the new additions from [2103](https://github.com/opensearch-project/OpenSearch/pull/2103), [1917](https://github.com/opensearch-project/OpenSearch/pull/1917), and [1916](https://github.com/opensearch-project/OpenSearch/pull/1916).
 
This documentation is for Open Search 1.3.0+.

***NOTE*** I did copy and modify some of [Elastic's Apache License 2.0 docs for interval queries](https://raw.githubusercontent.com/elastic/elasticsearch/v7.10.2/docs/reference/query-dsl/intervals-query.asciidoc). 

### Issues Resolved
#415 
 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by mattweber** [comment]
cc @dblock

**Comment by keithhc2** [comment]
Hi @mattweber, thanks so much for all the work here. As you said, lot of the content is ported over from the Elasticsearch documentation, which we’re not accepting at this time. That said, the source files are under the Apache 2.0 license, so we might change course here and start accepting them in the future. I’m going to close out the PR for now, but if you could keep your branch intact, I’d appreciate it. Thanks again.

**Comment by mattweber** [comment]
@keithhc2 that's a shame as it is going to be very hard for people to document their changes without having at least a base to work with.  I want to document my changes but I don't want to write the entire section on Interval queries.

**Comment by Naarcha-AWS** [comment]
@mattweber and @keithhc2: Would you both be okay if I go ahead and migrate this to an issue? That way, Keith or myself could loop back around to this and find a logical way to improve on what came before.

**Comment by mattweber** [comment]
@Naarcha-AWS sure, I have #415 already open.

**Pull request closed without merging**
