### PR TITLE
Updated documentation on innerHits of nested k-NN field

### LINKED ISSUE #8819: [DOC]Multi innerhit in nested k-NN field
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
Support of multiple inner hits for nested k-NN field

**Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
 2.19

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/k-NN/issues/2249
https://github.com/opensearch-project/k-NN/pull/2283

### PR DESCRIPTION
**Pull request by heemin32**
### Description
Updated documentation on innerHits of nested k-NN field

### Issues Resolved
Closes #8819

### Version
2.19

### Frontend features
N/A

### Checklist
- [X] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by heemin32** [comment]
@kolchfa-aws any update?

**Comment by kolchfa-aws** [comment]
Hi @heemin32, could you please tag me when ready for review next time? I will review this PR tomorrow. Thanks!

**Comment by heemin32** [comment]
> Hi @heemin32, could you please tag me when ready for review next time? I will review this PR tomorrow. Thanks!

Will do. Thanks!

**Comment by kolchfa-aws** [comment]
@heemin32 Doc review complete. Could you look over the PR and let me know if anything should be changed? Thanks!

**Comment by heemin32** [comment]
@kolchfa-aws LGTM. Thanks!

**Pull request merged**
