### PR TITLE
[Workload Management] Querygroup Lifecyle API docs

### LINKED ISSUE #8066: [DOC] Add Documentation for WorkloadManagement Settings
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request.
Adding documentation for workload management settings. As per this PR: https://github.com/opensearch-project/OpenSearch/pull/15028

***Version:** List the OpenSearch version to which this issue applies, e.g. 2.14, 2.12--2.14, or all.
2.x

### PR DESCRIPTION
**Pull request by kiranprakash154**
### Description
Adds QueryGroup LifeCycle API related docs
Depends on https://github.com/opensearch-project/documentation-website/pull/8228 to be merged.

### Issues Resolved
Closes #8066 

### Version
2.17

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Naarcha-AWS** [comment]
@kiranprakash154: I see that this PR is still in draft mode. Is it ready for review?

**Comment by Naarcha-AWS** [comment]
@kiranprakash154: Is this due for 2.18?

**Comment by Naarcha-AWS** [comment]
Will likely be closed by #8628, but keeping open to use as an additional resource.

**Comment by ruai0511** [comment]
This can be closed

**Pull request closed without merging**
