### PR TITLE
Update multi-data-sources.md with valid example for connection URL

### PR DESCRIPTION
**Pull request by tomuk5**
### Description
use a valid example for a connection URL - which would help users determine to connect to other remote Opensearch compatible data sources

### Issues Resolved
Provide valid example for feature

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Signed-off-by: Thomas Wing <tomuk5@msn.com>

### CODE REVIEW

**Review by peterzhuamazon — COMMENTED** [review]
Hi @tomuk5 ,

Why are we changing from 5601 port of OSD to 9200 port of OS?

Thanks.

**Comment by tomuk5** [comment]
Hi @peterzhuamazon so the example given is a valid format URL for entry into the Endpoint URL field.

The example given 'http://localhost:5601/app/management/opensearch-dashboards/dataSources' is not a valid URL for entry into the endpoint URL field.

**Review by vagimeli — APPROVED** [review]

**Comment by vagimeli** [comment]
> Hi @peterzhuamazon so the example given is a valid format URL for entry into the Endpoint URL field.
> 
> The example given
> 
> > http://localhost:5601/app/management/opensearch-dashboards/dataSources
> 
> is not a valid URL for entry into the endpoint URL field.


@peterzhuamazon @tomuk5 This is for OpenSearch Dashboards, not OpenSearch.  Typically, the URL is `http://localhost:5601/`. Please confirm what the correct URL should be.

**Comment by hdhalter** [comment]
@seraphjiang

**Comment by hdhalter** [comment]
@BionIT - Can you please review this? Thanks in advance!

**Review by seraphjiang — APPROVED** [review]
LGTM

**Pull request merged**
