### PR TITLE
Improve logging of the link checker

### PR DESCRIPTION
**Pull request by AMoo-Miki**
Signed-off-by: Miki <miki@amazon.com>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by hdhalter — APPROVED** [review]
Miki, is there anything we need to know to use the link checker?

**Review by alicejw-aws — APPROVED** [review]
LGTM, thanks for doing this!

**Comment by alicejw-aws** [comment]
> Miki, is there anything we need to know to use the link checker?

From 
bundle exec jekyll build 
this runs the LinkChecker

**Comment by alicejw-aws** [comment]
my apologies. was trying to close a comment and closed the PR by mistake! reopened now.

**Review by Naarcha-AWS — APPROVED** [review]

**Pull request merged**
