### PR TITLE
Add note about Data Prepper versus ingest processors

### PR DESCRIPTION
**Pull request by vagimeli**
### Description
Clarifies when to use Data Prepper instead of OpenSearch ingestion processors

### Issues Resolved
Closes https://github.com/opensearch-project/documentation-website/issues/6429

### Checklist
- [X] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by vagimeli** [comment]
@Naarcha-AWS Please review this PR at your availability. I added notes to clarify using Data Prepper processors versus OpenSearch ingestion processors. Thank you.

**Comment by vagimeli** [comment]
@Naarcha-AWS  Following up to get your doc review. Thanks!

**Review by Naarcha-AWS — APPROVED** [review]
LGTM.

**Review by dlvenable — APPROVED** [review]

**Review by natebower — APPROVED** [review]
LGTM

**Pull request merged**
