### PR TITLE
949: Added missing transform cluster privileges in privilege list

### PR DESCRIPTION
**Pull request by stevanbz**
Signed-off-by: Stevan Buzejic <buzejic.stevan@gmail.com>

### Description
Adds transform cluster related privileges to privilege list

### Issues Resolved
https://github.com/opensearch-project/documentation-website/issues/949

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Naarcha-AWS** [comment]
@stevanbz: Thank you for your contribution. Have you verified that these transform permissions function? And if so, for what versions?

**Comment by Naarcha-AWS** [comment]
Thanks @stevanbz. Just a heads up, your commit requires the DCO sign-off to pass the PR check.
See [fix DCO](https://github.com/src-d/guide/blob/9171d013c648236c39faabcad8598be3c0cf8f56/developer-community/fix-DCO.md#how-to-add-sign-offs-retroactively) for details.

We'll need you to sign off before you can merge, as well as resolving the merge conflict.

**Comment by stevanbz** [comment]
> 

Hi. Thanks for notifying me - I forgot to sign-off. I am resolving the conflicts now and I saw that new privilege naming is being used (at least for index management cluster related actions) where the opendistro keyword is being removed. I suppose I should follow the pattern for transform or? Tnx in advance

**Review by Naarcha-AWS — APPROVED** [review]

**Comment by Naarcha-AWS** [comment]
@stevanbz: Following up, you're correct that we're trying to remove `opendistro` endpoints and permissions when we can. However, the security plugin is an exception. I did verify these permissions within the code of the security plugin.

**Comment by Naarcha-AWS** [comment]
@stevanbz: I'm going to go ahead and close this and open a new PR.

**Comment by stevanbz** [comment]
Hi @Naarcha-AWS and tnx for the response. One question: did you manage to open new PR?
If so, can you pls send me the link to the PR? tnx in advance

**Pull request closed without merging**
