### PR TITLE
Update generate-certificates.md

### PR DESCRIPTION
**Pull request by ict-one-nl**
By default certificates are valid for 30 days, that's not useful, set it to 10 years.

### CODE REVIEW

**Comment by aetter** [comment]
Hey @ict-one-nl, thanks for reaching out (as always). The root certificate looks duplicative (we already have a `-days` value of 730), but others are on the `*-key.pem` lines look like they might indeed be necessary. To your knowledge, the keys also need the longer expiration date?

**Comment by ict-one-nl** [comment]
Hmm I need to test that, expired certs do however bring the cluster down, nodes won't communicate.

Will try to this this week.

**Comment by aetter** [comment]
Thanks a bunch. I'll try to take a look next week, as well. Some of the reading I've done indicates that keys don't expire, but maybe it's just a particular key format, or keys in a different context, etc. Testing will reveal all, I'm sure.

**Comment by ict-one-nl** [comment]
Difficult one to test, but after googling I found everyone using the -days option only on the request and not on the private keys. Think we should be alright with the proposed changes.

**Comment by aetter** [comment]
Hi @ict-one-nl I'm still running some tests here, which take 24 hours apiece while I wait for certs to expire. For keys, agreed, that was my finding, as well. OpenSSL doesn't even accept a `-days` option for them.

Between the CSR and the certificate itself, though, it doesn't make sense to me that they both accept a `-days` argument. It seems like we should only be specifying it in one place. For example, your PR would turn the admin certificate generation into:

```
openssl req -new  -days 3650 -key admin-key.pem -subj "/C=CA/ST=ONTARIO/L=TORONTO/O=ORG/OU=UNIT/CN=ADMIN" -out admin.csr
openssl x509 -req -in admin.csr -CA root-ca.pem -CAkey root-ca-key.pem -CAcreateserial -sha256 -out admin.pem -days 730
```

If we specify `-days` in both, does the 3650 value get overridden by the 730? If not, can we safely remove the 730? That's what I'm looking into.

**Comment by aetter** [comment]
OK I think I can say with confidence that the `-days` argument must go on the final certificate command and not the CSR command. If we use the admin certificate as an example, consider the following:

```
openssl req -new -key admin-key.pem -subj "/C=CA/ST=ONTARIO/L=TORONTO/O=ORG/OU=UNIT/CN=ADMIN" -out admin.csr -days 3650
openssl x509 -req -in admin.csr -CA root-ca.pem -CAkey root-ca-key.pem -CAcreateserial -sha256 -out admin.pem
```

Then run `openssl x509 -enddate -noout -in admin.pem`, and the expiration date is 30 days from today, not ten years. To get the expected ten years, run:

```
openssl req -new -key admin-key.pem -subj "/C=CA/ST=ONTARIO/L=TORONTO/O=ORG/OU=UNIT/CN=ADMIN" -out admin.csr
openssl x509 -req -in admin.csr -CA root-ca.pem -CAkey root-ca-key.pem -CAcreateserial -sha256 -out admin.pem -days 3650
```

So I'm open to changing the expiration date on the script certificates to something other than two years, but the `-days` argument appears to be in the right place. I'm going to close out this PR, but happy to keep discussing in this thread. 👍

**Comment by ict-one-nl** [comment]
Okay cool, I'll update my scripts and see if everything keeps working. Thanks for the effort!

**Pull request closed without merging**
