### PR TITLE
Added troubleshooting instructions for environment set up

### PR DESCRIPTION
**Pull request by GumpacG**
### Description
Added to the environment setup instructions to help contributors with potential issues.

### Issues Resolved
https://github.com/opensearch-project/documentation-website/issues/6800
https://github.com/opensearch-project/documentation-website/issues/6242

### Checklist
- [ ] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by hdhalter** [comment]
@AMoo-Miki - Can you give this a quick tech review? Thanks!

**Comment by AMoo-Miki** [comment]
Thanks.

**Review by AMoo-Miki — APPROVED** [review]

**Comment by Naarcha-AWS** [comment]
I consolidated the error and resolution steps into one bullet a piece.

**Comment by GumpacG** [comment]
@Naarcha-AWS Thanks! I've updated with your suggestions.

**Review by epugh — APPROVED** [review]

**Pull request merged**
