### PR TITLE
Add updated Cohere blueprints to connector blueprints section

### PR DESCRIPTION
**Pull request by tianjing-li**
### Description
_Describe what this change achieves._

In the `ml-commons` repo, these two PRs: https://github.com/opensearch-project/ml-commons/pull/1950 and https://github.com/opensearch-project/ml-commons/pull/1991 updated the existing Cohere blueprints to enable registering Cohere's /embed and /chat endpoints.

It merges the previous two embed blueprints into one, and adds a chat blueprint.

This PR updates the links provided in the main website docs.

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._

N/A

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by kolchfa-aws — COMMENTED** [review]
LGTM. Thank you, @tianjing-li!

**Comment by kolchfa-aws** [comment]
@tianjing-li Could you fix DCO so we can merge this PR?

**Comment by tianjing-li** [comment]
@kolchfa-aws DCO should be resolved now

**Review by kolchfa-aws — APPROVED** [review]
Thanks! Let's get this merged.

**Pull request merged**
