### PR TITLE
Fix broken links in 1.3

### PR DESCRIPTION
**Pull request by kolchfa-aws**
Fix broken links in 1.3

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
```
[Error] Found 1 dead link:
https://opensearch.org/docs/latest/breaking-changes/, linked to in ./_install-and-configure/upgrade-opensearch/index.md
```

This happens because the link checker believes this is a local link. To fix I suggest correcting `_config` to say `1.3` on this branch and not `latest`, which is the case. The other option is to exclude this link from the link checker explicitly (will need a little code), or create `/latest` in the source.

**Review by Naarcha-AWS — APPROVED** [review]
Approved, but should we remove the breaking changes link from the upgrades page? I don't think so, personally.

**Comment by kolchfa-aws** [comment]
No, we are not planning to remove it. We need to find a solution that works best in order for it not to be flagged.

**Comment by Naarcha-AWS** [comment]
> No, we are not planning to remove it. We need to find a solution that works best in order for it not to be flagged.

We could use the live breaking changes link. Alternatively, we could carry the file over to 1.3.

**Comment by dblock** [comment]
Can we turn this PR green by doing what I suggest? What are the downsides?

**Comment by kolchfa-aws** [comment]
@dblock I've implemented your suggestion (in _config.yml, changed baseurl to "/docs/1.3"). @AMoo-Miki Could you review when you get a chance to see if this is the best solution given our build process? Thanks!

**Comment by AMoo-Miki** [comment]
I am not a fan of changing the config in branches. The link checker used to have a way to identify external links; I think we should bring that back. Changing the config `baseurl` removes the predictable testing URL when contributors check out revisions of code; this will lead to confusion and annoyance.

**Comment by kolchfa-aws** [comment]
I'd like to merge this PR because it contains link fixes. I'll revert the config change for now until we come up with the best solution to differentiate local links from absolute ones in the link checker.

**Pull request merged**
