### PR TITLE
Add page for migrating to Dashboards

### PR DESCRIPTION
**Pull request by aetter**
### Description
[Describe what this change achieves]
 
### Issues Resolved
https://github.com/opensearch-project/documentation-website/issues/71
 
### Check List
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by aetter** [comment]
@tmarkley @kavilla

**Comment by dblock** [comment]
I don't know about the implementation details to review this, I think @tmarkley or maybe @mihirsoni?

**Comment by dblock** [comment]
@saratvemulapalli

**Comment by aetter** [comment]
I'm very happy to make changes based on reviewer feedback, but I'm merging now so that we have this content for 1.0.0.

**Comment by kavilla** [comment]
Hey thanks for this. Looks pretty good.

> Port your settings from `<kibana-dir>/config/kibana.yml` to `<dashboards-dir>/config/opensearch_dashboards.yml`.

I think to be safe, I would tell people to create a backup of kibana.yml. Just in case they moved their file and rename it.

> In general, settings with `elasticsearch` in their names map to `opensearch` (e.g. `elasticsearch.shardTimeout` and `opensearch.shardTimeout`) and settings with `kibana` in their names map to `opensearchDashboards` (e.g. `kibana.defaultAppId` and `opensearchDashboards.defaultAppId`). Most other settings use the same names.

This is true, thanks for putting that. But subsequent changes were made to allow for the previous settings to still work with a deprecation message. Should we mention as a note that they shouldn't have to rename the settings right away? We thought it was a better experience for people to just have to rename the file and it work out of the box with warning messages.

**Comment by aetter** [comment]
> This is true, thanks for putting that. But subsequent changes were made to allow for the previous settings to still work with a deprecation message. Should we mention as a note that they shouldn't have to rename the settings right away? We thought it was a better experience for people to just have to rename the file and it work out of the box with warning messages.

Got it, thanks for reviewing. I must have tested right before that change made its way in; I tried porting `kibana.yml` over as-is, and Dashboards failed to start. I'll test again later today and modify as necessary. In the meantime, I've updated the docs with a recommendation to take a backup.

**Pull request merged**
