### PR TITLE
Add support for linear in rank feature

### PR DESCRIPTION
**Pull request by Hronom**
Signed-off-by: Yevhen Tienkaiev <hronom@gmail.com>

### Description
Adding description for rank features functionality
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/977
https://github.com/opensearch-project/OpenSearch/pull/2725
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Naarcha-AWS** [comment]
@Hronom: Would you like this merged in before the v2.0.0 release?

**Comment by Hronom** [comment]
@Naarcha-AWS ideally I think we need to merge this after this PR https://github.com/opensearch-project/OpenSearch/pull/2725 merged, since there added support for some features that mentioned in documentation but not yet present in OpenSearch

**Comment by Hronom** [comment]
@Naarcha-AWS I see https://github.com/opensearch-project/OpenSearch/pull/2725 merged, please proceed with merging of this

**Comment by Naarcha-AWS** [comment]
@Hronom: Are you okay if I take over this PR to place my edits on top?

**Comment by Hronom** [comment]
@Naarcha-AWS totally ok

**Comment by hdhalter** [comment]
@Naarcha-AWS - is this ready for a doc review/approval?

**Pull request closed without merging**
