### PR TITLE
Edit ism example policy

### PR DESCRIPTION
**Pull request by 10000-ki**
### Description

make the ism example policy more clearly

previous pr : https://github.com/opensearch-project/documentation-website/pull/5821

### Issues Resolved
None

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by 10000-ki** [comment]
@andrross sorry i had a mistake so i made a new pr :( ..

I modified it based on the reviews you gave me

**Comment by 10000-ki** [comment]
https://github.com/opensearch-project/documentation-website/pull/5821#issuecomment-1867904390

> We'll need to change the policy details and diagram to match and also include the temperature details you have above. @10000-ki what do you think? Would you be willing to make those changes in this PR? I think @vagimeli can probably help with the diagram changes if needed.

@vagimeli 
If you don't mind, I'd appreciate it if you could modify the diagram to fit the above content

**Comment by andrross** [comment]
> @vagimeli If you don't mind, I'd appreciate it if you could modify the diagram to fit the above content

@vagimeli We'll need to make the following changes to [ism.png](https://github.com/opensearch-project/documentation-website/blob/main/images/ism.png):

- Change text "After 1 day" to "After 7 days"
- Change text "1. Set number of replicas to 5" to
> 1. Set number of replicas to 1
> 2. Move index to `warm` nodes

Can you help with this?

**Review by andrross — APPROVED** [review]

**Comment by hdhalter** [comment]
Hi @andrross - I've updated the image. Please let me know if you'd like any additional changes. Thanks! https://github.com/opensearch-project/documentation-website/pull/6020

**Review by vagimeli — APPROVED** [review]

**Comment by vagimeli** [comment]
@hdhalter Thanks for making the updates while I was OOO. I've doc reviewed. It needs a maintainer to approve the PR.

**Pull request merged**
