### PR TITLE
Update MAINTAINERS.md

### LINKED ISSUE #2878: Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

### PR DESCRIPTION
**Pull request by Naarcha-AWS**
Fixes #2878

### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by seanneumann — APPROVED** [review]

**Review by kolchfa-aws — APPROVED** [review]

**Comment by ananzh** [comment]
@gaiksaya  could you help us to update the permissions? we don't have admin permission. thx.

**Comment by gaiksaya** [comment]
Hi @ananzh the codeowners file and maintainers.md file do not match. Can you match them and tag me once that is merged? Wondering which file is the source of truth for updating the permissions.
Thanks!

**Comment by ananzh** [comment]
@gaiksaya Confirmed with @Naarcha-AWS and fixed this via this new PR https://github.com/opensearch-project/documentation-website/pull/3831 (merged). Pls help to check the permissions and comment here or in the new PR. Thanks a lot for the help.

**Comment by gaiksaya** [comment]
Permissions are already up to date now: https://github.com/opensearch-project/documentation-website/issues/2878#issuecomment-1516967711
Thanks!

**Pull request merged**
