### PR TITLE
Adding sample configuration for auth_type and aws_iam

### PR DESCRIPTION
**Pull request by naveentatikonda**
Signed-off-by: Naveen Tatikonda <navtat@amazon.com>

### Description
Adding sample configurations for auth_type and aws_iam in the output plugin 
 
### Issues Resolved
https://github.com/opensearch-project/logstash-output-opensearch/issues/79
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by aetter** [comment]
Thanks a bunch @naveentatikonda. Does this need to wait for an upcoming release, or can it go in now?

Rather than an extended back and forth, I plan to just merge it make some tweaks to the wording in subsequent commits. 👍

**Review by aetter — APPROVED** [review]

**Comment by naveentatikonda** [comment]
> Thanks a bunch @naveentatikonda. Does this need to wait for an upcoming release, or can it go in now?
> 
> Rather than an extended back and forth, I plan to just merge it make some tweaks to the wording in subsequent commits. 👍

Thank you Andrew for reviewing and approving this PR. This is for an upcoming release. The code is merged to Main but it is under AppSec review for a Pen-Test.

**Comment by aetter** [comment]
Sounds great @naveentatikonda, just let me know when we should merge.

**Comment by naveentatikonda** [comment]
> Sounds great @naveentatikonda, just let me know when we should merge.

Sure, Thank you.

**Comment by VijayanB** [comment]
@ashwinkumar12345 This can be merged

**Review by ashwinkumar12345 — APPROVED** [review]

**Review by keithhc2 — APPROVED** [review]

**Pull request merged**
