### PR TITLE
clients: python: link to API reference docs

### PR DESCRIPTION
**Pull request by CameronNemo**
### Description
Links to API reference docs for the python client from the main website.

### Issues Resolved
Partially addresses https://github.com/opensearch-project/opensearch-py/issues/171

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Naarcha-AWS** [comment]
@CameronNemo: Your commit requires the DCO sign-off to pass the PR check.
See [fix DCO](https://github.com/src-d/guide/blob/9171d013c648236c39faabcad8598be3c0cf8f56/developer-community/fix-DCO.md#how-to-add-sign-offs-retroactively) for details.

**Comment by CameronNemo** [comment]
there is definitely a Signed-off-by in the commit message, although I used the Web UI for this change so maybe I typod or something. maybe the email is wrong because github is using it's obfuscated email...

**Comment by keithhc2** [comment]
@CameronNemo It didn't work the last time I tried to sign off using the web UI, so my assumption is it's not implemented there yet. If you don't want to mess around with rebasing and amending commits, you can cut a new branch, make your commits, and then use the `-s` flag in the Git CLI to sign off. Alternatively, using the [Chrome extension](https://github.com/scottrigby/dco-gh-ui) also works.

**Comment by Naarcha-AWS** [comment]
Closing this in favor of adding something similar in a different PR.

**Pull request closed without merging**
