### PR TITLE
Add support for linear in rank feature

### PR DESCRIPTION
**Pull request by Hronom**
### Description
Added documentation for rank feature/features
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/977
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Please don't merge until the code is merged.

**Comment by Hronom** [comment]
@dblock please check, since feature merged

**Comment by dblock** [comment]
@aetter could you please take a look?

**Comment by aetter** [comment]
Hi @Hronom, sorry for the slow reply here, and thanks so much for all the work. This content appears to be ported over from the Elasticsearch documentation, which we’re not accepting at this time. That said, the source files are under the Apache 2.0 license, so we might change course here and start accepting them in the future. I’m going to close out the PR for now, but if you could keep your branch intact, I’d appreciate it. Thanks again.

**Comment by Hronom** [comment]
@aetter I will keep it, also I can try to write it by myself and create separate branch, will it be ok? Or we blocked by Elasticsearch license completely?

**Comment by aetter** [comment]
Hi @Hronom, assuming the content was ported over from the Apache 2.0 AsciiDoc files in 7.10.2, it's not a licensing issue. It's just not how we're handling the documentation at this time. At present, we're looking for original work based on testing (and code analysis, when testing isn't practical).

So if you have a thorough understanding of the feature and want to take a crack at explaining it in your own words, with copy and pasted sample requests from your own testing, yes, that'd be amazing. I get that it's a lot of work, so even a walkthrough or non-comprehensive content would be much-appreciated. 👍

**Comment by Hronom** [comment]
@aetter please can you actually re-open, we need to have this in documentation of OpenSearch so this becomes well known feature.

Can you consult in side Amazon if it possible to use that documents? 
Since as you mention: they under the Apache 2.0

**Comment by Hronom** [comment]
@aetter please can you actually re-open, we need to have this in documentation of OpenSearch so this becomes well known feature.

Can you consult in side Amazon if it possible to use that documents? 
Since as you mention: they under the Apache 2.0

cc @dblock

**Pull request closed without merging**
