### PR TITLE
Updated index permissions as per customer request #20230726

### PR DESCRIPTION
**Pull request by eugene7421**
## Description
A customer submitted a query in relation to this page of the documentation:
https://opensearch.org/docs/latest/security/access-control/permissions/

### Customer query: 
Index permissions could have a description or something - x

### Answer to customers query:
A new  index permissions table was added to the documents, with descriptions of the index permissions included.

## Issues Resolved
This ticket addresses **one part** of https://github.com/opensearch-project/documentation-website/issues/4314

## Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by hdhalter** [comment]
@scrawfor99 - Can you please review for technical accuracy? Thanks!

**Review by scrawfor99 — APPROVED** [review]
Signing off on technical accuracy--I thought that @kolchfa-aws had made some changes detailing this same info before however. The info added is correct but mostly restates the permission paths. 

I am sure this is valuable for some but examples like:

```
 `indices:admin/aliases` |  Permission related to index aliases.  See also [Index aliases]( https://opensearch.org/docs/latest/im-plugin/index-alias/ ) |
| `indices:admin/aliases/get` |  Permission to get index aliases.  See also [Index aliases]( https://opensearch.org/docs/latest/im-plugin/index-alias/ ) |
```
are somewhat repetitive. 

I am not sure how we want to balance beginner-friendliness vs. brevity but I think we should consider when we may be going too far to address the feedback of one user at the cost of the general documentation.

**Comment by leanneeliatra** [comment]
> Signing off on technical accuracy--I thought that @kolchfa-aws had made some changes detailing this same info before however. The info added is correct but mostly restates the permission paths.
> 
> I am sure this is valuable for some but examples like:
> 
> ```
>  `indices:admin/aliases` |  Permission related to index aliases.  See also [Index aliases]( https://opensearch.org/docs/latest/im-plugin/index-alias/ ) |
> | `indices:admin/aliases/get` |  Permission to get index aliases.  See also [Index aliases]( https://opensearch.org/docs/latest/im-plugin/index-alias/ ) |
> ```
> 
> are somewhat repetitive.
> 
> I am not sure how we want to balance beginner-friendliness vs. brevity but I think we should consider when we may be going too far to address the feedback of one user at the cost of the general documentation.

I see your point @scrawfor99 , do you think it's okay to go ahead with these changes as they are, or should we remove the repetitiveness, in the places it's very repetitive we can just include the first explanation.

Let me know your thoughts.

**Comment by hdhalter** [comment]
IMHO, I think it's fine to leave the descriptions, especially since they link to further information. They prevents the reader from having to interpret each command. Thanks, Leanne!

**Comment by leanneeliatra** [comment]
> IMHO, I think it's fine to leave the descriptions, especially since they link to further information. They prevents the reader from having to interpret each command. Thanks, Leanne!

Thanks for confirming @hdhalter.

I have fixed the reviewdog issues, there are [some remaining] reviewdog (https://github.com/opensearch-project/documentation-website/pull/6404/files) issues being flagged @scrawfor99. Where there is an _ 
The reviewdog suggestion seems unnecessary / not correct. Can we ignore it in this case and proceed? Thanks

**Review by Leannelb — APPROVED** [review]

**Comment by leanneeliatra** [comment]
Thanks @Naarcha-AWS for the updates.

I have fixed one small reviewdog issue and now, the remaining reviewdog issues do not need to be fixed.

Can this PR please be merged now?

**Pull request merged**
