### PR TITLE
Update link checker

### PR DESCRIPTION
**Pull request by kolchfa-aws**
Add red warning/error color and change workflow from raising an exception to system exit.

### Checklist
- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by AMoo-Miki — APPROVED** [review]

**Review by vagimeli — APPROVED** [review]
LGTM

**Review by ariamarble — APPROVED** [review]

**Comment by Naarcha-AWS** [comment]
Waiting on another review from @AMoo-Miki to verify that the linkchecker still works after a couple of fixes.

**Comment by dblock** [comment]
Superseded with https://github.com/opensearch-project/documentation-website/pull/3584.

**Comment by kolchfa-aws** [comment]
Closing because everything will be implemented in #3584

**Pull request closed without merging**
