### PR TITLE
Plugins page revamp

### LINKED ISSUE #909: [DOC] Refactor of plugins page to prevent versioning issues during release process
**What do you want to do?**

Originally this was raised with the following purpose: 
`Add a section to the `Available plugins` table https://opensearch.org/docs/latest/opensearch/install/plugins/ for OS 1.3.4`

However, it looks like this has just exposed an issue in the release process where these manually-entered plugin versions are losing parity due to how we handle back port merges. Based on a discussion with another team member, it sounds like it's particularly annoying when minor versions are released for a previous major version (I believe that's what was said).

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Version 1.3.4 has been released but we don't have a corresponding row in the table for plugin versions.

### PR DESCRIPTION
**Pull request by JeffH-AWS**
### Description
Refactor of plugins page to make it easier to maintain and more readable to the user. Until now it's just been a huge HTML table that is difficult to maintain across so many site versions. Instead it will be replaced with a static table that lists official/managed plugins that are packaged with OpenSearch.

### Issues Resolved
Fixes #909 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by cwillum — APPROVED** [review]
Looks good.

**Review by kolchfa-aws — APPROVED** [review]
Looks good. Thank you, Jeff!

**Comment by JeffH-AWS** [comment]
Thanks everyone!

**Comment by JeffH-AWS** [comment]
Ran into errors/unfamiliar territory with some of those commands.  Instead of going through all of that I'm resubmitting a PR with the correct backport labels.  I know the triggerbot won't mess it up!

**Pull request merged**
