### PR TITLE
Add documentation for Crypto plugin

### LINKED ISSUE #2995: [DOC] Client Side Encryption in OpenSearch
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** 
We need to add a description for a new plugin which will provide support for client side encryption in OpenSearch. This is a placeholder issue and doc content will be updated later.

**What other resources are available?**
Link to the feature proposal : https://github.com/opensearch-project/OpenSearch/issues/6353

### PR DESCRIPTION
**Pull request by cwillum**
### Description
A new Crypto plugin for client side encryption and decryption of data for remote transfer / remote store.

### Issues Resolved
Fixes #2995 

### Checklist
- [ ] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by cwillum** [comment]
A first draft has been sent for tech review. But this includes some last questions, which will probably require changes.

**Comment by cwillum** [comment]
@vikasvb90 Could have a look at this for technical accuracy. Also, there's one outstanding question about the Cypto plugin repo. Do you have a link to this yet? Thanks.

**Comment by cwillum** [comment]
Crypto plugin has been pushed to 2.10.

**Comment by cwillum** [comment]
Development team is currently refining the plugin for OpenSearch applications. No documentation needed for 2.10.

**Comment by hdhalter** [comment]
I'm assuming that we should not include this in the release notes? I removed the flag.

**Comment by hdhalter** [comment]
The issue was closed, so closing this PR.

**Pull request closed without merging**
