### PR TITLE
Update snapshot-restore.md

### PR DESCRIPTION
**Pull request by ict-one-nl**
Setting seems deprecated. With it present clusters fails to start with message it does not recognise this setting.

### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._

### Checklist
- [ ] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kolchfa-aws** [comment]
Thanks, @ict-one-nl! @bowenlan-amzn Could you tech review this PR please?

**Comment by kolchfa-aws** [comment]
@jed326 Would you be able to review this PR?

**Comment by jed326** [comment]
@kolchfa-aws sorry for the late response. 

I still see this setting in the code: https://github.com/opensearch-project/OpenSearch/blob/e3542011cd9584c354405ba6cbf9a31ced7bc5ce/plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java#L238-L243

@ict-one-nl can you provide some more details of how you did the setup?

**Comment by ict-one-nl** [comment]
Okay, it's kind of weird;

Config: 
```
#s3.client.default.disable_chunked_encoding: false # Disables chunked encoding for compatibility with some storage services, but you probably don't need to change this value.
s3.client.default.endpoint: scality02.xxxx.nl:443 # S3 has alternate endpoints, but you probably don't need to change this value.
s3.client.default.max_retries: 3 # number of retries if a request fails
s3.client.default.path_style_access: true # whether to use the deprecated path-style bucket URLs.
#You probably don't need to change this value, but for more information, see https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#path-style-access.
s3.client.default.protocol: https # http or https
s3.client.default.read_timeout: 50s # the S3 connection timeout
s3.client.default.use_throttle_retries: true 
s3.client.default.region: us-east-2 #lijkt verplicht
```

Remove the comment on s3.client.default.disable_chunked_encoding:

image

image

Comment it out:

image

everything is fine

**Comment by msfroh** [comment]
@ict-one-nl , are you able to confirm whether the setting works as part of a repository creation request?

Regardless, I agree with this specific PR -- it shouldn't be documented as an opensearch.yml setting.

**Review by msfroh — APPROVED** [review]

**Review by kolchfa-aws — APPROVED** [review]
Thank you, @ict-one-nl!

**Pull request merged**
