### PR TITLE
Update index-codecs.md

### PR DESCRIPTION
**Pull request by sandervandegeijn**
qat_deflate does not work on 2.14, it does on 2.15.

2.14:

{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "unknown value for [index.codec] must be one of [default, lz4, best_compression, zlib] but was: qat_deflate"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "unknown value for [index.codec] must be one of [default, lz4, best_compression, zlib] but was: qat_deflate"
  },
  "status": 400
}

2.15:
{
  "acknowledged": true,
  "shards_acknowledged": true,
  "index": "x"
}

### Issues Resolved
-

### Version
2.14+

### Frontend features
- 

### Checklist
- [*] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and subject to the [Developers Certificate of Origin](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by sarthakaggarwal97** [comment]
+1 to this. The feature was not release in 2.14.
Thanks @sandervandegeijn

**Review by sarthakaggarwal97 — APPROVED** [review]

**Review by hdhalter — APPROVED** [review]

**Comment by hdhalter** [comment]
Actually, @sandervandegeijn, we need to update this line too:

**As of OpenSearch 2.14**, hardware-accelerated compression codecs for the `DEFLATE` and `LZ4` compression algorithms are available. These hardware-accelerated codecs are available on the latest 4th and 5th Gen Intel®️ Xeon®️ processors running Linux kernel 3.10 and later. For all other systems and platforms, the codecs use that platform's corresponding software implementations.

Can you please make that change?

**Comment by sandervandegeijn** [comment]
Updated everything to 2.15!

**Comment by hdhalter** [comment]
Hi, @sandervandegeijn, can you please fix DCO? Thanks!

**Comment by sandervandegeijn** [comment]
Done!

**Pull request merged**
